server:
  port: 8003
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    active: local

mybatis-plus:
  mapper-locations: classpath:beijing/*.xml
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql